### ISSUE TITLE
Exception when updating product

### ISSUE THREAD

**Issue by AxelAlemanD** [AxelAlemanD/Web-system-natural-medicines#3]
#### Description
I am working on a system to manage a business selling natural products.
The products are made up of name, description, image url, price and quantity. Also, it has a many-to-many relationship with the Categories table.
When updating a product, it throws the error shown below.
The changes are made but the error appears.
The image is not updated.

#### Screenshots
![error_message](https://user-images.githubusercontent.com/99099658/166087782-8dfbb784-a9ed-4851-aa98-6791658d9d3c.png)

#### Files
The problem is in the products controller ([ProductsController.php](https://github.com/AxelAlemanD/Web-system-natural-medicines/blob/ProductsModule/app/Http/Controllers/ProductsController.php)) of the **ProductsModule** branch.
It is probably necessary to check the relationships in the Products model ([Product.php](https://github.com/AxelAlemanD/Web-system-natural-medicines/blob/ProductsModule/app/Models/Product.php)) and Categories ([Category.php](https://github.com/AxelAlemanD/Web-system-natural-medicines/blob/ProductsModule/app/Models/Category.php)).

#### To Reproduce
To update product information:
* You enter the Products module
* Click on any product
* Later the option to edit product is started and some changes are made
* After clicking on the save button the mentioned error is displayed.

**Note:** Apparently the values ​​are updated, except for the url_image.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Verify relationship between Products and Categories
- [x] Check what values ​​are being received
- [x] Check what values ​​are expected when updating
- [ ] Try to fix the problem temporarily with a try..catch

**Comment by AxelAlemanD** [comment]
**SOLUTION:** Only moved the code snippet that updates categories after product update :smiley:
